server:
  port: 8081
spring:
  application:
    name: knowledge-agent-user
  datasource:
    url: jdbc:mysql://localhost:3306/knowledge_agent?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
dubbo:
  protocol:
    name: knowledge-agent-user
    port: 28081
  registry:
    address: nacos://127.0.0.1:8848
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开发环境打印SQL
